version: "3.8"

services:
  web:
    image: superdot/web
    command: nginx -g "daemon off;"
    env_file: .env.frontend
    restart: always
    build: 
      context: ${FRONTEND_REPO}
      dockerfile: Dockerfile
    ports: 
      - "${WEB_PORT}:80"
    depends_on:
      - backend
  backend:
    image: superdot/backend
    command: node ./build/server.js
    env_file: .env.backend
    build: 
      context: ${BACKEND_REPO}
      dockerfile: Dockerfile
    volumes:
      - ./storage:/home/app/build/storage/uploads
    ports: 
      - "${BACKEND_PORT}:3000"
    depends_on:
      - mongodb
    networks:
      - infra-network
  mongodb:
    image: superdot/db
    restart: always
    build: 
      context: ./db/
      dockerfile: Dockerfile
    volumes:
      - ./db/data:/data/db
    ports: 
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: "superdot"
    networks:
      - infra-network

networks:
  infra-network:
    driver: bridge